#!/bin/bash

SESSION=fanCtrl
tmux="/usr/local/bin/tmux -2 "

SCRIPT=`realpath $0`
SCRIPTPATH=`dirname $SCRIPT`

if [ -z "$1" ]; then
  echo "usage: $0 <port>"
  exit 1
fi

$SCRIPTPATH/fanCtrl.cron.sh $1

$tmux attach -t $SESSION
